"""db bucket field

Revision ID: 093dbd4937ec
Revises: c5f1b8431345
Create Date: 2025-10-10 18:59:08.828451

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "093dbd4937ec"
down_revision: Union[str, None] = "c5f1b8431345"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feeds", schema=None) as batch_op:
        batch_op.add_column(sa.Column("bucket", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feeds", schema=None) as batch_op:
        batch_op.drop_column("bucket")
    # ### end Alembic commands ###
