"""remove feed frequency score

Revision ID: 0f2e07db0a84
Revises: 3d9ad62e0140
Create Date: 2023-08-11 20:35:29.069673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f2e07db0a84'
down_revision: Union[str, None] = '3d9ad62e0140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'frequency_rank')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('frequency_rank', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True))
    # ### end Alembic commands ###
