"""user kindle credentials

Revision ID: 205c07370100
Revises: 2ab46a53ab1b
Create Date: 2023-10-23 11:13:32.975780

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '205c07370100'
down_revision: Union[str, None] = '2ab46a53ab1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kindle_credentials', schema=None) as batch_op:
        batch_op.create_unique_constraint('kindle_user_unique', ['user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kindle_credentials', schema=None) as batch_op:
        batch_op.drop_constraint('kindle_user_unique', type_='unique')

    # ### end Alembic commands ###
