"""added indexes

Revision ID: 23ea8c9e83ce
Revises: 6dbb6a64bc24
Create Date: 2023-08-08 18:27:35.240433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23ea8c9e83ce'
down_revision: Union[str, None] = '6dbb6a64bc24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_entries_username'), 'entries', ['username'], unique=False)
    op.create_index(op.f('ix_feeds_folder'), 'feeds', ['folder'], unique=False)
    op.create_index(op.f('ix_feeds_name'), 'feeds', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feeds_name'), table_name='feeds')
    op.drop_index(op.f('ix_feeds_folder'), table_name='feeds')
    op.drop_index(op.f('ix_entries_username'), table_name='entries')
    # ### end Alembic commands ###
