"""rename entry body to content_short

Revision ID: 317a05ddf805
Revises: 4ab856aa1a08
Create Date: 2024-01-02 18:09:09.988404

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '317a05ddf805'
down_revision: Union[str, None] = '4ab856aa1a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.alter_column('body', new_column_name='content_short')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.alter_column('content_short', new_column_name='body')

    # ### end Alembic commands ###
