"""add feed frequency score

Revision ID: 3d9ad62e0140
Revises: 60868ddf9ce9
Create Date: 2023-08-10 13:27:20.515845

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3d9ad62e0140'
down_revision: Union[str, None] = '60868ddf9ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('frequency_rank', sa.Integer(), nullable=True, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'frequency_rank')
    # ### end Alembic commands ###
