"""add entry viewed field

Revision ID: 50c51018af18
Revises: 958ea127f204
Create Date: 2023-09-21 10:38:08.642263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c51018af18'
down_revision: Union[str, None] = '958ea127f204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('viewed', sa.TIMESTAMP(), nullable=True))
    op.create_index(op.f('ix_entries_viewed'), 'entries', ['viewed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entries_viewed'), table_name='entries')
    op.drop_column('entries', 'viewed')
    # ### end Alembic commands ###
