"""remove entry deleted

Revision ID: 50c516bc475b
Revises: 50c51018af18
Create Date: 2023-09-21 17:14:58.774781

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '50c516bc475b'
down_revision: Union[str, None] = '50c51018af18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entries_deleted', table_name='entries')

    with op.batch_alter_table("entries") as batch_op:
        batch_op.drop_column('deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('deleted', sa.TIMESTAMP(), nullable=True))
    op.create_index('ix_entries_deleted', 'entries', ['deleted'], unique=False)
    # ### end Alembic commands ###
