"""added feed views

Revision ID: 60868ddf9ce9
Revises: 23ea8c9e83ce
Create Date: 2023-08-09 18:55:30.797239

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '60868ddf9ce9'
down_revision: Union[str, None] = '23ea8c9e83ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('views', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'views')
    # ### end Alembic commands ###
