"""add indexes for new entry attributes

Revision ID: 72ac46dfbe54
Revises: 66aa18ecbbfa
Create Date: 2023-08-18 13:18:15.166091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ac46dfbe54'
down_revision: Union[str, None] = '66aa18ecbbfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_entries_deleted'), 'entries', ['deleted'], unique=False)
    op.create_index(op.f('ix_entries_favorited'), 'entries', ['favorited'], unique=False)
    op.create_index(op.f('ix_entries_pinned'), 'entries', ['pinned'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entries_pinned'), table_name='entries')
    op.drop_index(op.f('ix_entries_favorited'), table_name='entries')
    op.drop_index(op.f('ix_entries_deleted'), table_name='entries')
    # ### end Alembic commands ###
