"""remove user url

Revision ID: 80dc4b94cdf0
Revises: 50c516bc475b
Create Date: 2023-09-24 13:51:40.658656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80dc4b94cdf0'
down_revision: Union[str, None] = '50c516bc475b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_column('user_url')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_url', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
