"""mastodon app and account tables

Revision ID: 92f907c96e8b
Revises: f52cbbaeab22
Create Date: 2023-11-24 13:36:48.607430

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '92f907c96e8b'
down_revision: Union[str, None] = 'f52cbbaeab22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mastodon_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('feeds_masto_account_id', 'mastodon_accounts', [
                                    'mastodon_account_id'], ['id'])
        batch_op.drop_column('access_token')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('feeds_masto_account_id', type_='foreignkey')
        batch_op.drop_column('mastodon_account_id')

    # ### end Alembic commands ###
