"""add rss feed filters

Revision ID: 958ea127f204
Revises: e2aaf62aeed0
Create Date: 2023-09-19 21:22:39.309794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958ea127f204'
down_revision: Union[str, None] = 'e2aaf62aeed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('filters', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'filters')
    # ### end Alembic commands ###
