"""remove feed score

Revision ID: af19df375216
Revises: 75f0f3beb7fa
Create Date: 2023-12-16 19:26:02.908578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af19df375216'
down_revision: Union[str, None] = '75f0f3beb7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))

    # ### end Alembic commands ###
