"""remove js enabled field

Revision ID: b91a4a54b490
Revises: af4c6cd4ec3a
Create Date: 2023-10-03 11:34:59.353965

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b91a4a54b490'
down_revision: Union[str, None] = 'af4c6cd4ec3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.drop_column('javascript_enabled')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('javascript_enabled', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
