"""rename entry date columns

Revision ID: de5bb7dd36db
Revises: a7680d17c088
Create Date: 2024-01-02 13:52:37.962221

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'de5bb7dd36db'
down_revision: Union[str, None] = 'a7680d17c088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_index('entry_updated_ts')
        batch_op.alter_column('remote_created', new_column_name='display_date')
        batch_op.alter_column('remote_updated', new_column_name='sort_date')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.alter_column('display_date', new_column_name='remote_created')
        batch_op.alter_column('sort_date', new_column_name='remote_updated')

    # ### end Alembic commands ###
