"""remove backlogged

Revision ID: f11ef7901ceb
Revises: fc7cea04e4ca
Create Date: 2024-05-24 16:26:22.169909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f11ef7901ceb'
down_revision: Union[str, None] = 'fc7cea04e4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_index('ix_entries_backlogged')
        batch_op.drop_column('backlogged')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backlogged', sa.TIMESTAMP(), nullable=True))
        batch_op.create_index('ix_entries_backlogged', ['backlogged'], unique=False)

    # ### end Alembic commands ###
