"""add index to entry title

Revision ID: f411849d887d
Revises: 093dbd4937ec
Create Date: 2025-10-19 21:57:28.188836

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f411849d887d"
down_revision: Union[str, None] = "093dbd4937ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_entries_title"), ["title"], unique=False)

    with op.batch_alter_table("feeds", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_feeds_created"), ["created"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feeds", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feeds_created"))

    with op.batch_alter_table("entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entries_title"))

    # ### end Alembic commands ###
