"""entry backlogged date

Revision ID: fc7cea04e4ca
Revises: 29fa12e6895d
Create Date: 2024-01-09 12:24:20.180315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc7cea04e4ca'
down_revision: Union[str, None] = '29fa12e6895d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backlogged', sa.TIMESTAMP(), nullable=True))
        batch_op.create_index(batch_op.f('ix_entries_backlogged'), ['backlogged'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entries_backlogged'))
        batch_op.drop_column('backlogged')

    # ### end Alembic commands ###
