SECRET_KEY = b'\xffN\xcfX\xbc\xa9V\x8b*_zFB\xb9\xfa\x1d'
SQLALCHEMY_DATABASE_URI = "sqlite:///feedi.db"
# SQLALCHEMY_ENGINE_OPTIONS = {'connect_args': {'timeout': 15}}
DEBUG = True
TEMPLATES_AUTO_RELOAD = True

RSS_SKIP_RECENTLY_UPDATED_MINUTES = 15
RSS_SKIP_OLDER_THAN_DAYS = 5
MASTODON_FETCH_LIMIT = 50
